# Generated by Django 4.2.3 on 2023-07-11 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'keranjang',
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Haircare', 'Haircare'), ('Bodycare', 'Bodycare'), ('Skincare', 'Skincare')], max_length=100)),
                ('no_wa', models.CharField(max_length=20)),
                ('total_pembayaran', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('keranjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.keranjang')),
            ],
            options={
                'db_table': 'penjualan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('Haircare', 'Haircare'), ('Bodycare', 'Bodycare'), ('Skincare', 'Skincare')], max_length=100)),
                ('foto_produk', models.ImageField(upload_to='produk/')),
            ],
            options={
                'db_table': 'produk',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengirim', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pending', max_length=20)),
                ('bukti_transfer', models.ImageField(upload_to='bukti_transfer/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('keranjang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.keranjang')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.penjualan')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaksi',
            },
        ),
        migrations.AddField(
            model_name='penjualan',
            name='produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.produk'),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.produk')),
            ],
            options={
                'db_table': 'pembeliann',
            },
        ),
        migrations.CreateModel(
            name='KeranjangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('keranjang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.keranjang')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminn.produk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'keranjangitem',
            },
        ),
        migrations.AddField(
            model_name='keranjang',
            name='items',
            field=models.ManyToManyField(through='adminn.KeranjangItem', to='adminn.produk'),
        ),
        migrations.AddField(
            model_name='keranjang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
